gra: Main.cpp AllyCard.cpp Player.cpp SpellCard.cpp FactoryOfCards.cpp Model.cpp Card.cpp Controller.cpp Table.cpp Common.cpp
	g++ -o gra Main.cpp AllyCard.cpp Player.cpp SpellCard.cpp FactoryOfCards.cpp Model.cpp Card.cpp Controller.cpp Table.cpp Common.cpp
